# Generated by Django 5.0.3 on 2024-03-06 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer360', '0002_interaction_social_media_alter_interaction_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='social_media',
        ),
        migrations.AddField(
            model_name='customer',
            name='social_media',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
